default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: matsutter_development
test:
  <<: *default
  database: matsutter_test
  
production:
  <<: *default
  database: matsutter_production
  username: matsutter
  password: <%= ENV['MATSUTTER_DATABASE_PASSWORD'] %>
